Currently I define the prior in the nodeVariable class, but then I use the output of TabularCPD().values to actually use the prior.

I want to use only one or the other

It turns out that in PGMPY, a prior is essentially a CPT with only one parent state. Hence it should be a 2D array of shape (len(bins), 1)

In [1]:
import numpy as np
from pgmpy.factors.discrete import TabularCPD
import src.models.helpers as mh

In [11]:
Var = mh.variableNode("Var", 1, 6, 1, prior={"type": "uniform"})
Var.cpt[:,0]

array([0.2, 0.2, 0.2, 0.2, 0.2])

In [4]:
cpd = TabularCPD(
    variable=HFEV1.name,
    variable_card=len(HFEV1.bins),
    values=HFEV1.cpt,
    evidence=[],
    evidence_card=[],
)
cpd.get_values()

/var/folders/zq/v2r6yn111s3gpdf8lzf72xvw0000gn/T/ipykernel_1505/4162985829.py:1: DeprecationWarning: `product` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `prod` instead.
  cpd = TabularCPD(


array([[0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2]])

In [ ]:
HFEV1.bins

array([1., 2., 3., 4., 5., 6.])

In [10]:
# P(FEV1) =
bins = HFEV1.bins
1 / len(bins)
prior = np.array([1 / len(bins)] * len(bins)).reshape(len(bins), 1)

In [28]:
[
    f"[{round(bins[i], 2)}; {bins[-1]+1 if i == len(bins)-1 else round(bins[i+1], 2)})"
    for i in range(len(bins))
]

['[1.0; 2.0)', '[2.0; 3.0)', '[3.0; 4.0)', '[4.0; 5.0)']

In [29]:
np.arange(2, 4, 1)

array([2, 3])

In [23]:
bins

array([1., 2., 3., 4.])

In [26]:
[i for i in range(len(bins))]

[0, 1, 2, 3]